// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/myAction.ts";
import * as $$$0 from "./loaders/myLoader.ts";
import * as $$$1 from "./loaders/tags.ts";
import * as $$$$$$0 from "./sections/mySection.tsx";
import * as $$$$$$1 from "./sections/tags.tsx";

const manifest = {
  "loaders": {
    "app-tags/loaders/myLoader.ts": $$$0,
    "app-tags/loaders/tags.ts": $$$1,
  },
  "sections": {
    "app-tags/sections/mySection.tsx": $$$$$$0,
    "app-tags/sections/tags.tsx": $$$$$$1,
  },
  "actions": {
    "app-tags/actions/myAction.ts": $$$$$$$$$0,
  },
  "name": "app-tags",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
